# 1. Cart Service Secret
apiVersion: v1
kind: Secret
metadata:
  name: cart-secret
  namespace: default
type: Opaque
stringData:
  DB_HOST: "mysql-svc"
  DB_PORT: "3306"
  DB_USERNAME: "shop_user"
  DB_PASSWORD: "shop_password"
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  JWT_SECRET_KEY: "mySecretKeyForJWTTokenGeneration2024"
  JWT_EXPIRATION: "86400000"
  CORS_ALLOWED_ORIGINS: "*"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE"
  CORS_ALLOWED_HEADERS: "*"
  LOG_LEVEL: "DEBUG"
  AWS_DEFAULT_REGION: "us-east-2"

---
# 2. Cart Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      serviceAccountName: s3-sa
      containers:
      - name: cart-service
        image: 862016452072.dkr.ecr.us-east-2.amazonaws.com/kubox:cart-service-v3
        ports:
        - containerPort: 8084
          name: http
        envFrom:
        - secretRef:
            name: cart-secret
        env:
        - name: DB_NAME
          value: "cart_db"
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          periodSeconds: 5
          failureThreshold: 40
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"

---
# 3. Cart Service
apiVersion: v1
kind: Service
metadata:
  name: cart-svc
  namespace: default
spec:
  selector:
    app: cart-service
  ports:
  - port: 8084
    targetPort: 8084
    name: http
  type: ClusterIP
