apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kubox-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
  - secretName: kubox-common-secret
    type: Opaque
    data:
    - objectName: "kubox-common-db-host"
      key: DB_HOST
    - objectName: "kubox-common-db-port"
      key: DB_PORT
    - objectName: "kubox-common-db-username"
      key: DB_USERNAME
    - objectName: "kubox-common-db-password"
      key: DB_PASSWORD
    - objectName: "kubox-common-redis-host"
      key: REDIS_HOST
    - objectName: "kubox-common-redis-port"
      key: REDIS_PORT
    - objectName: "kubox-common-jwt-secret"
      key: JWT_SECRET_KEY
    - objectName: "kubox-common-jwt-expiration"
      key: JWT_EXPIRATION
    - objectName: "kubox-common-cors-origins"
      key: CORS_ALLOWED_ORIGINS
    - objectName: "kubox-common-cors-methods"
      key: CORS_ALLOWED_METHODS
    - objectName: "kubox-common-cors-headers"
      key: CORS_ALLOWED_HEADERS
    - objectName: "kubox-common-log-level"
      key: LOG_LEVEL
    - objectName: "kubox-common-aws-region"
      key: AWS_DEFAULT_REGION
  - secretName: kubox-bootpay-secret
    type: Opaque
    data:
    - objectName: "kubox-bootpay-api-url"
      key: BOOTPAY_API_URL
    - objectName: "kubox-bootpay-app-id"
      key: BOOTPAY_APPLICATION_ID
    - objectName: "kubox-bootpay-private-key"
      key: BOOTPAY_PRIVATE_KEY
  - secretName: kubox-mysql-secret
    type: Opaque
    data:
    - objectName: "kubox-mysql-root-password"
      key: MYSQL_ROOT_PASSWORD
    - objectName: "kubox-mysql-user"
      key: MYSQL_USER
    - objectName: "kubox-mysql-password"
      key: MYSQL_PASSWORD
    - objectName: "kubox-mysql-database"
      key: MYSQL_DATABASE
  parameters:
    objects: |
      - objectName: "kubox/common"
        objectType: "secretsmanager"
        jmesPath:
        - path: "DB_HOST"
          objectAlias: "kubox-common-db-host"
        - path: "DB_PORT"
          objectAlias: "kubox-common-db-port"
        - path: "DB_USERNAME"
          objectAlias: "kubox-common-db-username"
        - path: "DB_PASSWORD"
          objectAlias: "kubox-common-db-password"
        - path: "REDIS_HOST"
          objectAlias: "kubox-common-redis-host"
        - path: "REDIS_PORT"
          objectAlias: "kubox-common-redis-port"
        - path: "JWT_SECRET_KEY"
          objectAlias: "kubox-common-jwt-secret"
        - path: "JWT_EXPIRATION"
          objectAlias: "kubox-common-jwt-expiration"
        - path: "CORS_ALLOWED_ORIGINS"
          objectAlias: "kubox-common-cors-origins"
        - path: "CORS_ALLOWED_METHODS"
          objectAlias: "kubox-common-cors-methods"
        - path: "CORS_ALLOWED_HEADERS"
          objectAlias: "kubox-common-cors-headers"
        - path: "LOG_LEVEL"
          objectAlias: "kubox-common-log-level"
        - path: "AWS_DEFAULT_REGION"
          objectAlias: "kubox-common-aws-region"
      - objectName: "kubox/bootpay"
        objectType: "secretsmanager"
        jmesPath:
        - path: "BOOTPAY_API_URL"
          objectAlias: "kubox-bootpay-api-url"
        - path: "BOOTPAY_APPLICATION_ID"
          objectAlias: "kubox-bootpay-app-id"
        - path: "BOOTPAY_PRIVATE_KEY"
          objectAlias: "kubox-bootpay-private-key"
      - objectName: "kubox/mysql"
        objectType: "secretsmanager"
        jmesPath:
        - path: "MYSQL_ROOT_PASSWORD"
          objectAlias: "kubox-mysql-root-password"
        - path: "MYSQL_USER"
          objectAlias: "kubox-mysql-user"
        - path: "MYSQL_PASSWORD"
          objectAlias: "kubox-mysql-password"
        - path: "MYSQL_DATABASE"
          objectAlias: "kubox-mysql-database"
