apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kubox-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
  - secretName: kubox-common-secret
    type: Opaque
    data:
    - objectName: "DB_HOST"
      key: DB_HOST
    - objectName: "DB_PORT"
      key: DB_PORT
    - objectName: "DB_USERNAME"
      key: DB_USERNAME
    - objectName: "DB_PASSWORD"
      key: DB_PASSWORD
    - objectName: "REDIS_HOST"
      key: REDIS_HOST
    - objectName: "REDIS_PORT"
      key: REDIS_PORT
    - objectName: "JWT_SECRET_KEY"
      key: JWT_SECRET_KEY
    - objectName: "JWT_EXPIRATION"
      key: JWT_EXPIRATION
    - objectName: "CORS_ALLOWED_ORIGINS"
      key: CORS_ALLOWED_ORIGINS
    - objectName: "CORS_ALLOWED_METHODS"
      key: CORS_ALLOWED_METHODS
    - objectName: "CORS_ALLOWED_HEADERS"
      key: CORS_ALLOWED_HEADERS
    - objectName: "LOG_LEVEL"
      key: LOG_LEVEL
    - objectName: "AWS_DEFAULT_REGION"
      key: AWS_DEFAULT_REGION
  - secretName: kubox-bootpay-secret
    type: Opaque
    data:
    - objectName: "BOOTPAY_API_URL"
      key: BOOTPAY_API_URL
    - objectName: "BOOTPAY_APPLICATION_ID"
      key: BOOTPAY_APPLICATION_ID
    - objectName: "BOOTPAY_PRIVATE_KEY"
      key: BOOTPAY_PRIVATE_KEY
  - secretName: kubox-mysql-secret
    type: Opaque
    data:
    - objectName: "MYSQL_ROOT_PASSWORD"
      key: MYSQL_ROOT_PASSWORD
    - objectName: "MYSQL_USER"
      key: MYSQL_USER
    - objectName: "MYSQL_PASSWORD"
      key: MYSQL_PASSWORD
    - objectName: "MYSQL_DATABASE"
      key: MYSQL_DATABASE
  parameters:
    objects: |
      - objectName: "kubox/common"
        objectType: "secretsmanager"
        jmesPath:
        - path: "DB_HOST"
          objectAlias: "DB_HOST"
        - path: "DB_PORT"
          objectAlias: "DB_PORT"
        - path: "DB_USERNAME"
          objectAlias: "DB_USERNAME"
        - path: "DB_PASSWORD"
          objectAlias: "DB_PASSWORD"
        - path: "REDIS_HOST"
          objectAlias: "REDIS_HOST"
        - path: "REDIS_PORT"
          objectAlias: "REDIS_PORT"
        - path: "JWT_SECRET_KEY"
          objectAlias: "JWT_SECRET_KEY"
        - path: "JWT_EXPIRATION"
          objectAlias: "JWT_EXPIRATION"
        - path: "CORS_ALLOWED_ORIGINS"
          objectAlias: "CORS_ALLOWED_ORIGINS"
        - path: "CORS_ALLOWED_METHODS"
          objectAlias: "CORS_ALLOWED_METHODS"
        - path: "CORS_ALLOWED_HEADERS"
          objectAlias: "CORS_ALLOWED_HEADERS"
        - path: "LOG_LEVEL"
          objectAlias: "LOG_LEVEL"
        - path: "AWS_DEFAULT_REGION"
          objectAlias: "AWS_DEFAULT_REGION"
      - objectName: "kubox/bootpay"
        objectType: "secretsmanager"
        jmesPath:
        - path: "BOOTPAY_API_URL"
          objectAlias: "BOOTPAY_API_URL"
        - path: "BOOTPAY_APPLICATION_ID"
          objectAlias: "BOOTPAY_APPLICATION_ID"
        - path: "BOOTPAY_PRIVATE_KEY"
          objectAlias: "BOOTPAY_PRIVATE_KEY"
      - objectName: "kubox/mysql"
        objectType: "secretsmanager"
        jmesPath:
        - path: "MYSQL_ROOT_PASSWORD"
          objectAlias: "MYSQL_ROOT_PASSWORD"
        - path: "MYSQL_USER"
          objectAlias: "MYSQL_USER"
        - path: "MYSQL_PASSWORD"
          objectAlias: "MYSQL_PASSWORD"
        - path: "MYSQL_DATABASE"
          objectAlias: "MYSQL_DATABASE"
