# 1. Product Service Secret
apiVersion: v1
kind: Secret
metadata:
  name: product-secret
  namespace: default
type: Opaque
stringData:
  DB_HOST: "mysql-svc"
  DB_PORT: "3306"
  DB_USERNAME: "shop_user"
  DB_PASSWORD: "shop_password"
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  JWT_SECRET_KEY: "mySecretKeyForJWTTokenGeneration2024"
  JWT_EXPIRATION: "86400000"
  BOOTPAY_API_URL: "https://api.bootpay.co.kr"
  BOOTPAY_APPLICATION_ID: "688989d686cd66f61255b60b"
  BOOTPAY_PRIVATE_KEY: "P4s4fN5fI3l1zRJNqvBdpKuSjW+dYx111VXXqWHayZU="
  CORS_ALLOWED_ORIGINS: "https://www.kubox.shop,https://api.kubox.shop"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE"
  CORS_ALLOWED_HEADERS: "*"
  LOG_LEVEL: "DEBUG"
  AWS_DEFAULT_REGION: "us-east-2"

---
# 2. Product Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      serviceAccountName: s3-sa
      containers:
      - name: product-service
        image: 862016452072.dkr.ecr.us-east-2.amazonaws.com/kubox:product-service-v1
        ports:
        - containerPort: 8081
          name: http
        envFrom:
        - secretRef:
            name: product-secret
        env:
        - name: DB_NAME
          value: "product_db"
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          periodSeconds: 5
          failureThreshold: 40
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"

---
# 3. Product Service
apiVersion: v1
kind: Service
metadata:
  name: product-svc
  namespace: default
spec:
  selector:
    app: product-service
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  type: ClusterIP
