# Cart Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: app-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      serviceAccountName: kubox-secrets-sa
      containers:
      - name: cart-service
        image: 862016452072.dkr.ecr.us-east-2.amazonaws.com/kubox:cart-service-v2
        ports:
        - containerPort: 8084
          name: http
        envFrom:
        - secretRef:
            name: kubox-common-secret
        env:
        - name: DB_NAME
          value: "cart_db"
        volumeMounts:
        - name: secrets-store
          mountPath: /mnt/secrets
          readOnly: true
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          periodSeconds: 5
          failureThreshold: 40
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: kubox-secrets

---
# Cart Service
apiVersion: v1
kind: Service
metadata:
  name: cart-svc
  namespace: app-services
spec:
  selector:
    app: cart-service
  ports:
  - port: 8084
    targetPort: 8084
    name: http
  type: ClusterIP
