# Payment Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: app-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      serviceAccountName: kubox-secrets-sa
      containers:
      - name: payment-service
        image: 862016452072.dkr.ecr.ap-northeast-2.amazonaws.com/kubox:payment-service-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
          name: http
        envFrom:
        - secretRef:
            name: kubox-common-secret
        - secretRef:
            name: kubox-bootpay-secret
        env:
        - name: DB_NAME
          value: "payment_db"
        volumeMounts:
        - name: secrets-store
          mountPath: /mnt/secrets
          readOnly: true
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          periodSeconds: 10
          failureThreshold: 30
          timeoutSeconds: 5
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          periodSeconds: 15
          timeoutSeconds: 2
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          periodSeconds: 15
          timeoutSeconds: 2
          failureThreshold: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: kubox-secrets

---
# Payment Service
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
  namespace: app-services
spec:
  selector:
    app: payment-service
  ports:
  - port: 8083
    targetPort: 8083
    name: http
  type: ClusterIP

---
# Payment Service HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-service-hpa
  namespace: app-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # behavior:
  #   scaleUp:
  #     stabilizationWindowSeconds: 60
  #     policies:
  #     - type: Percent
  #       value: 100
  #       periodSeconds: 15
  #   scaleDown:
  #     stabilizationWindowSeconds: 300
  #     policies:
  #     - type: Percent
  #       value: 10
  #       periodSeconds: 60


